[package]
name = "bob"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "31.0.0"
wasmtime-wasi = "31.0.0"
wit-bindgen-rt = { version = "0.41.0", features = ["bitflags"] }

[package.metadata.component]
package = "component:crypto"

[package.metadata.component.dependencies]